version: "3.8"

services:
  app:
    container_name: app
    working_dir: /app
    build: ./app
    volumes:
      - ./app:/app
    image: node:18-alpine
    command: sh -c "yarn start:dev"
    ports:
      - 3000:3000

  spa:
    container_name: spa
    working_dir: /spa
    build: ./spa
    volumes:
      - ./spa:/spa
    image: node:18-alpine
    command: sh -c "yarn dev"
    ports:
      - 5173:5173